# Generated by Django 5.2 on 2025-04-12 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('pincode', models.PositiveIntegerField()),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingid', models.IntegerField(primary_key=True, serialize=False)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('guests', models.PositiveIntegerField(default=1)),
                ('totalprice', models.FloatField()),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomid', models.IntegerField(primary_key=True, serialize=False)),
                ('roomtype', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Suite', 'Suite')], max_length=50)),
                ('description', models.TextField()),
                ('price_per_night', models.FloatField()),
                ('image', models.ImageField(upload_to='room_photos')),
                ('is_available', models.BooleanField(default=True)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('receiptid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('totalprice', models.FloatField()),
                ('bookingid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.booking')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('roomid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.room')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='roomid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.room'),
        ),
    ]
